added nonzero retval to ps1

diff --git a/bashrc_rc b/bashrc_rc
--- a/bashrc_rc
+++ b/bashrc_rc
@@ -4,10 +4,13 @@ export TERM='xterm-256color'
 export PATH="$PATH:/sbin"
 
 parse_git_branch() {
+	TMPRET=$?
 	git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/\1/'
+	return $TMPRET
 }
 
 function parse_git_dirty {
+	TMPRET=$?
 	status=`git status 2> /dev/null`
 	dirty=`echo -n "${status}" 2> /dev/null | grep -q "modified:" 2> /dev/null; echo "$?"`
 	untracked=`echo -n "${status}" 2> /dev/null | grep -q "Untracked files" 2> /dev/null; echo "$?"`
@@ -31,25 +34,34 @@ function parse_git_dirty {
 		bits="${bits}>"
 	fi
 	echo "${bits}"
+	return $TMPRET
 }
+
+#echo "❤"
 
 nonzero_return() {
 	RETVAL=$?
-	[ $RETVAL -eq 1 ] && echo " ⏎ $RETVAL "
+	if [ $RETVAL -ne 0 ]
+	then
+		echo "⏎$RETVAL"
+	else
+		echo "❤"
+	fi
 }
-
 
 #Russ PS1
 #PS1="\n$TIMECOL\@ $USERCOL \u $ATCOL@ $HOSTCOL\h $PATHCOL \w $RETURNCOL\`nonzero_return\`$BRANCHCOL \`parse_git_branch\`\`parse_git_dirty\` $NC\n\\$ "
-PS1="[\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\W\[\033[00m\]] \`parse_git_branch\`\`parse_git_dirty\` \$ \[\033[01;31m\]❤ \[\e[m\]"
+#PS1="[\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\W\[\033[00m\]] \`parse_git_branch\`\`parse_git_dirty\` \$ \[\033[01;31m\]❤ \[\e[m\]"
+#export PS1="[\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\W\[\033[00m\]] \`parse_git_branch\`\`parse_git_dirty\` \$ \[\033[01;31m\]\`nonzero_return\` \[\e[m\]"
+export PS1="[\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\W\[\033[00m\]] \`parse_git_branch\`\`parse_git_dirty\` \$ \[\033[01;31m\]\`nonzero_return\` \[\e[m\]"
 
 
 
 #sync dotfiles
 (
-    cd ~/dotfiles
+	cd ~/dotfiles
 	git pull -q
-	 exit
+	exit
 )& disown
 
 
