cool git PS1

diff --git a/bashrc_rc b/bashrc_rc
--- a/bashrc_rc
+++ b/bashrc_rc
@@ -1,6 +1,47 @@
 #export statements
 export EDITOR=vim
-export PS1="[\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\W\[\033[00m\]]\$ "
+
+parse_git_branch() {
+	git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/\1/'
+}
+
+function parse_git_dirty {
+	status=`git status 2> /dev/null`
+	dirty=`echo -n "${status}" 2> /dev/null | grep -q "modified:" 2> /dev/null; echo "$?"`
+	untracked=`echo -n "${status}" 2> /dev/null | grep -q "Untracked files" 2> /dev/null; echo "$?"`
+	ahead=`echo -n "${status}" 2> /dev/null | grep -q "Your branch is ahead of" 2> /dev/null; echo "$?"`
+	newfile=`echo -n "${status}" 2> /dev/null | grep -q "new file:" 2> /dev/null; echo "$?"`
+	renamed=`echo -n "${status}" 2> /dev/null | grep -q "renamed:" 2> /dev/null; echo "$?"`
+	bits=''
+	if [ "${dirty}" == "0" ]; then
+		bits="${bits}⚡"
+	fi
+	if [ "${untracked}" == "0" ]; then
+		bits="${bits}?"
+	fi
+	if [ "${newfile}" == "0" ]; then
+		bits="${bits}+"
+	fi
+	if [ "${ahead}" == "0" ]; then
+		bits="${bits}*"
+	fi
+	if [ "${renamed}" == "0" ]; then
+		bits="${bits}>"
+	fi
+	echo "${bits}"
+}
+
+nonzero_return() {
+	RETVAL=$?
+	[ $RETVAL -eq 1 ] && echo " ⏎ $RETVAL "
+}
+
+
+#Russ PS1
+#PS1="\n$TIMECOL\@ $USERCOL \u $ATCOL@ $HOSTCOL\h $PATHCOL \w $RETURNCOL\`nonzero_return\`$BRANCHCOL \`parse_git_branch\`\`parse_git_dirty\` $NC\n\\$ "
+PS1="[\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\W\[\033[00m\]] \`parse_git_branch\`\`parse_git_dirty\` \$ "
+
+
 
 #sync rcFiles
 (
